translation of choosing-the-state-structure page in Hindi
reactjs/hi.react.dev pull request #221
Opened 2023-03-03 05:19 UTC by BrijenMakwana

Translation of choosing-the-state-structure page in Hindi

Review Progress:

- [ ] Overview
- [ ] Principles for structuring state 
- [ ] Group related state 
- [ ] Avoid contradictions in state 
- [ ] Avoid redundant state 
- [ ] Avoid duplication in state 
- [ ] Avoid deeply nested state 
- [ ] Recap
- [ ] Challenges

2023-03-07 12:55 UTC, arshadkazmi42 requested changes
Thank you for taking this up.

I have added review till line 102.

Lets get these fixed and post that we can continue with the review.
To know more about our review guides lines refer #23

2023-03-07 12:55 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +State को अच्छी तरह से स्ट्रक्टरिंग करने से, एक कौम्पोनॅन्ट में मॉडिफाई और डीबग करने में आनंददायक अंतर बन सकता है, जबकि एक ऐसा कौम्पोनॅन्ट एक निरंतर बग के स्रोत के रूप में दिखाई देगा। यहां state को स्
```suggestion
अछि तरह से State को स्ट्रक्चर करने से एक कौम्पोनॅन्ट के बीच अंतर पता लग सकता है जो चंगेस और डिबग करने में आराम दायक हो, और एक जो बग का एक निरंतर स्त्रोत ह। यहाँ दिए गए टिप्स state स्ट्रक्चर करते समय ध्यान में रखें।
```

2023-03-07 12:55 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +* State का ऑर्गनाइज़ करते समय किन बातों से बचना चाहिए
```suggestion
* State को ऑर्गनाइज़ करते समय किन बातों से बचना चाहिए
```

2023-03-07 12:55 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +जब आप एक कौम्पोनॅन्ट लिखते हैं जो कुछ state रखता है, तो आपको कितने state वेरिएबल्स का उपयोग करना है और उनके डेटा का शेप क्या होना चाहिए, इसके बारे में आपको चुनाव करना होगा। हालांकि एक सबऑप्टिमल state
```suggestion
जब आप एक कौम्पोनॅन्ट लिखते हैं जिसमें state का इस्तेमाल होता है, तो आपको इसके बारे में सोचना होता है की कितने state वेरिएबल्स का उपयोग करना है और उनके डेटा का शेप क्या होना चाहिए। हालांकि एक सबऑप्टिमल state स्ट्रक्चर के साथ भी सही प्रोग्राम लिखना पॉसिबल है, कुछ प्रिंसिपल्स हैं जो आपको बेहतर चोइसस बनाने के लिए गाइड कर सकते हैं:
```

2023-03-07 12:55 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +1. **ग्रुप से संबंधित state।** यदि आप हमेशा एक ही समय में दो या दो से ज्यादा state वेरिएबल्स को अपडेट करते हैं, तो उन्हें एक state वेरिएबल में मर्ज करें।
```suggestion
1. **ग्रुप से संबंधित state।** यदि आप हमेशा एक ही समय में दो या दो से ज्यादा state वेरिएबल्स को अपडेट करते हैं, तो उन्हें एक state वेरिएबल में मर्ज करने के बारे में सोचें।
```

2023-03-07 12:55 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +3. **रेडंडेंट state से बचें।** यदि आप रेंडरिंग के दौरान कौम्पोनॅन्ट के props या उसके मौजूदा state वेरिएबल्स से कुछ जानकारी कैलकुलेट कर सकते हैं, तो आपको उस जानकारी को उस कौम्पोनॅन्ट के state में नहीं
```suggestion
3. **रिडेन्डेन्ट state से बचें।** यदि आप रेंडरिंग के दौरान कौम्पोनॅन्ट के props या उसके मौजूदा state वेरिएबल्स से कुछ जानकारी कैलकुलेट कर सकते हैं, तो आपको उस जानकारी को उस कौम्पोनॅन्ट के state में नहीं रखना चाहिए।
```

2023-03-07 12:55 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +4. **State में डुप्लिकेशन से बचें।.** जब एक ही डेटा को कई state वेरिएबल्स के बीच, या नेस्टेड ऑब्जेक्ट्स के बीच डुप्लिकेट किया जाता है, तो उन्हें सिंक में रखना मुश्किल होता है। जब आप कर सकते हैं तो डु
```suggestion
4. **State में डुप्लिकेशन से बचें।** जब एक ही डेटा को कई state वेरिएबल्स के बीच, या नेस्टेड ऑब्जेक्ट्स के बीच डुप्लिकेट किया जाता है, तो उन्हें सिंक में रखना मुश्किल होता है। जब आप कर सकते हैं तो डुप्लिकेशन कम करें।
```

2023-03-07 12:55 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +इन प्रिंसिपल्स के पीछे उद्देश्य है _गलतियों को पेश किए बिना state को अपडेट करना आसान बनाएं_। State से रेडंडेंट और डुप्लिकेट डेटा को हटाने से यह सुनिश्चित करने में मदद मिलती है कि इसके सभी टुकड़े सिंक
```suggestion
इन प्रिंसिपल्स के पीछे उद्देश्य है *गलतियों को पेश किए बिना state को अपडेट करना आसान बनाएं*। State से रिडेन्डेन्ट और डुप्लिकेट डेटा को हटाने से यह सुनिश्चित करने में मदद मिलती है कि इसके सभी टुकड़े सिंक में रहें। यह उसी तरह है जैसे एक डेटाबेस इंजीनियर बग की संभावना को कम करने के लिए [डेटाबेस स्ट्रक्चर को "normalize"](https://docs.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description) करना चाहता है। अल्बर्ट आइंस्टीन की व्याख्या करने के लिए, **"अपने state को जितना हो सके उतना सरल बनाएं - लेकिन सरलतम नहीं।"**
```

2023-03-07 12:55 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +तकनीकी तौर पर, आप इनमें से किसी भी तरीके का इस्तेमाल कर सकते हैं। लेकिन **अगर कुछ दो state वेरिएबल्स हमेशा एक साथ बदलते हैं, तो यह एक अच्छा विचार हो सकता है कि उन्हें एक state वेरिएबल में एकीकृत किया
```suggestion
तकनीकी तौर पर, आप इनमें से किसी भी तरीके का इस्तेमाल कर सकते हैं। लेकिन **अगर कुछ दो state वेरिएबल्स हमेशा एक साथ बदलते हैं, तो यह एक अच्छा विचार हो सकता है कि उन्हें एक state वेरिएबल में एकीकृत रखा जाये**। तब आप उन्हें हमेशा सिंक में रखना नहीं भूलते हैं, जैसे कि इस उदाहरण में, जहां कर्सर को आगे बढ़ाना लाल डॉट के दोनों कोआर्डिनेट्स को अपडेट करता है:
```

2023-03-07 12:55 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +एक और मामला जहां आप डेटा को किसी ऑब्जेक्ट या array में समूहित करेंगे, जब आप नहीं जानते कि आपको state के कितने अलग-अलग टुकड़ों की ज़रूरत होगी। उदाहरण के लिए, यह तब मददगार होता है जब आपके पास एक फॉर्म
```suggestion
एक और मामला जहां आप डेटा को किसी ऑब्जेक्ट या array में समूहित करेंगे, जब आप नहीं जानते कि आपको state के कितने अलग-अलग टुकड़ों की ज़रूरत होगी। उदाहरण के लिए, यह तब मददगार होता है जब आपके पास एक फॉर्म होता है जहां उपयोगकर्ता कस्टम फ़ील्ड ऐड कर सकता है।
```

2023-03-07 13:53 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +* State का ऑर्गनाइज़ करते समय किन बातों से बचना चाहिए
👍

2023-03-07 13:54 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +जब आप एक कौम्पोनॅन्ट लिखते हैं जो कुछ state रखता है, तो आपको कितने state वेरिएबल्स का उपयोग करना है और उनके डेटा का शेप क्या होना चाहिए, इसके बारे में आपको चुनाव करना होगा। हालांकि एक सबऑप्टिमल state
👍

2023-03-07 13:54 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +1. **ग्रुप से संबंधित state।** यदि आप हमेशा एक ही समय में दो या दो से ज्यादा state वेरिएबल्स को अपडेट करते हैं, तो उन्हें एक state वेरिएबल में मर्ज करें।
👍

2023-03-07 13:54 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +3. **रेडंडेंट state से बचें।** यदि आप रेंडरिंग के दौरान कौम्पोनॅन्ट के props या उसके मौजूदा state वेरिएबल्स से कुछ जानकारी कैलकुलेट कर सकते हैं, तो आपको उस जानकारी को उस कौम्पोनॅन्ट के state में नहीं
👍

2023-03-07 13:54 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +4. **State में डुप्लिकेशन से बचें।.** जब एक ही डेटा को कई state वेरिएबल्स के बीच, या नेस्टेड ऑब्जेक्ट्स के बीच डुप्लिकेट किया जाता है, तो उन्हें सिंक में रखना मुश्किल होता है। जब आप कर सकते हैं तो डु
👍

2023-03-07 13:55 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +इन प्रिंसिपल्स के पीछे उद्देश्य है _गलतियों को पेश किए बिना state को अपडेट करना आसान बनाएं_। State से रेडंडेंट और डुप्लिकेट डेटा को हटाने से यह सुनिश्चित करने में मदद मिलती है कि इसके सभी टुकड़े सिंक
👍

2023-03-07 13:55 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +तकनीकी तौर पर, आप इनमें से किसी भी तरीके का इस्तेमाल कर सकते हैं। लेकिन **अगर कुछ दो state वेरिएबल्स हमेशा एक साथ बदलते हैं, तो यह एक अच्छा विचार हो सकता है कि उन्हें एक state वेरिएबल में एकीकृत किया
👍

2023-03-07 14:01 UTC, BrijenMakwana commented
> Thank you for taking this up.
> 
> I have added review till line 102.
> 
> Lets get these fixed and post that we can continue with the review. To know more about our review guides lines refer #23

I have made the changes that you have asked 👍🏻

2023-03-08 11:45 UTC, arshadkazmi42 requested changes
Thank you for working on the fixes.

I have added some more reviews till line 375.

Let's get these fixed and post that we can continue further with the review.

2023-03-08 11:45 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +हालांकि यह कोड काम करता है, लेकिन यह "नामुमकिन" states के लिए दरवाजा खुला छोड़ देता है। उदाहरण के लिए, यदि आप एक साथ `setIsSent` और `setIsSending` को कॉल करना भूल जाते हैं, तो आप ऐसी स्थिति में हो सक
```suggestion
हालांकि यह कोड काम करता है, लेकिन यह "नामुमकिन" states के लिए दरवाजा खुला छोड़ देता है। उदाहरण के लिए, यदि आप एक साथ `setIsSent` और `setIsSending` को कॉल करना भूल जाते हैं, तो आप ऐसी स्थिति में हो सकते हैं जहाँ `isSending` और` isSent` दोनों एक ही समय में `true` हैं। आपका कौम्पोनॅन्ट जितना कॉम्प्लेक्स होगा, यह समझना उतना ही मुश्किल होगा कि क्या हुआ था।
```

2023-03-08 11:45 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +**चूँकि `isSending` और` isSent` एक ही समय में कभी भी `true` नहीं होने चाहिए, इसलिए बेहतर होगा कि उन्हें एक `status` state वेरिएबल से बदल दिया जाए जो _तीन_ मान्य states में से एक ले सकता है:** `'typin
```suggestion
**चूँकि `isSending` और` isSent` एक ही समय में कभी भी `true` नहीं होने चाहिए, इसलिए बेहतर होगा कि उन्हें एक `status` state वेरिएबल से बदल दिया जाए जो *तीन* वैलिड states में से एक ले सकता है:** `'typing'` (शुरुआती), `'sending'`, और `'sent'`:
```

2023-03-08 11:45 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +पढ़ने की क्षमता के लिए आप अभी भी कुछ कॉन्स्टेंट्स घोषित कर सकते हैं:
```suggestion
पढ़ने की क्षमता के लिए आप अभी भी कुछ कॉन्स्टेंट्स डिक्लेअर कर सकते हैं:
```

2023-03-08 11:45 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +इस फॉर्म में तीन state वेरिएबल्स हैं: `firstName`, `lastName`, and `fullName`. हालांकि, `fullName` रिडेन्डेन्ट है। **आप रेंडर के दौरान हमेशा `firstName` और`lastName` से `fullName` की गणना कर सकते हैं
```suggestion
इस फॉर्म में तीन state वेरिएबल्स हैं: `firstName`, `lastName`, and `fullName`। हालांकि, `fullName` रिडेन्डेन्ट है। **आप रेंडर के दौरान हमेशा `firstName` और`lastName` से `fullName` को कैलकुलेट कर सकते हैं, इसलिए इसे state से हटा दें।**
```

2023-03-08 11:45 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +यहां, `fullName` एक state वेरिएबल _नहीं_ है। इसके बजाय, इसकी गणना रेंडर के दौरान की जाती है:
```suggestion
यहां, `fullName` एक state वेरिएबल *नहीं* है। इसके बजाय, इसको कैलकुलेट रेंडर के दौरान किया जाता है:
```

2023-03-08 11:45 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +nge handler को इसे अपडेट करने के लिए कुछ विशेष करने की ज़रूरत नहीं है। जब आप `setFirstName` या `setLastName` को कॉल करते हैं, तो आप फिर से रेंडर ट्रिगर करते हैं, और फिर अगले `fullName` की गणना नए डेट
```suggestion
चेंज हैंडलर्स को इसे अपडेट करने के लिए कुछ विशेष करने की ज़रूरत नहीं है। जब आप `setFirstName` या `setLastName` को कॉल करते हैं, तो आप फिर से रेंडर ट्रिगर करते हैं, और फिर अगले `fullName` की गणना नए डेटा से की जाएगी।
```

2023-03-08 11:45 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +यहाँ, एक `color` state वेरिएबल को `messageColor` prop में इनिशियलाइज़ किया गया है। समस्या यह है कि **यदि पैरेंट कौम्पोनॅन्ट बाद में `messageColor` का एक अलग वैल्यू पास करता है (उदाहरण के लिए, `'blue'
```suggestion
यहाँ, एक `color` state वेरिएबल को `messageColor` prop में इनिशियलाइज़ किया गया है। समस्या यह है कि **यदि पैरेंट कौम्पोनॅन्ट बाद में `messageColor` का एक अलग वैल्यू पास करता है (उदाहरण के लिए, `'blue'` के बजाय `'red'`), तो `color` *state वेरिएबल* अपडेट नहीं होगा!** State केवल पहले रेंडर के दौरान इनिशलाइज्ड होता है।
```

2023-03-08 11:45 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +यही कारण है कि state वेरिएबल में कुछ prop को "मिररिंग" करने से कन्फ्यूजन पैदा हो सकता है। इसके बजाय, सीधे अपने कोड में `messageColor` props का उपयोग करें। यदि आप इसे छोटा नाम देना चाहते हैं, तो कॉन्स
```suggestion
यही कारण है कि state वेरिएबल में कुछ prop को "मिरर" करने से कन्फ्यूजन पैदा हो सकता है। इसके बजाय, सीधे अपने कोड में `messageColor` props का उपयोग करें। यदि आप इसे छोटा नाम देना चाहते हैं, तो कॉन्स्टेंट का उपयोग करें:
```

2023-03-08 11:45 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +State में "मिररिंग" prop तभी समझ में आता है जब आप किसी विशिष्ट prop के लिए सभी अपडेट को अनदेखा करना चाहते हैं। प्रथा के अनुसार, prop नाम को `initial` या `default` से शुरू करें ताकि यह स्पष्ट किया जा
```suggestion
State में prop को "मिरर" करना तभी समझ में आता है जब आप किसी विशिष्ट prop के लिए सभी अपडेट को अनदेखा करना चाहते हैं। कन्वेंशन के अनुसार, prop के नाम को `initial` या `default` से शुरू करें ताकि यह स्पष्ट किया जा सके कि इसके नए वैल्यूज़ को अनदेखा किया गया है:
```

2023-03-08 12:32 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +हालांकि यह कोड काम करता है, लेकिन यह "नामुमकिन" states के लिए दरवाजा खुला छोड़ देता है। उदाहरण के लिए, यदि आप एक साथ `setIsSent` और `setIsSending` को कॉल करना भूल जाते हैं, तो आप ऐसी स्थिति में हो सक
👍

2023-03-08 12:32 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +**चूँकि `isSending` और` isSent` एक ही समय में कभी भी `true` नहीं होने चाहिए, इसलिए बेहतर होगा कि उन्हें एक `status` state वेरिएबल से बदल दिया जाए जो _तीन_ मान्य states में से एक ले सकता है:** `'typin
👍

2023-03-08 12:32 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +पढ़ने की क्षमता के लिए आप अभी भी कुछ कॉन्स्टेंट्स घोषित कर सकते हैं:
👍

2023-03-08 12:32 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +इस फॉर्म में तीन state वेरिएबल्स हैं: `firstName`, `lastName`, and `fullName`. हालांकि, `fullName` रिडेन्डेन्ट है। **आप रेंडर के दौरान हमेशा `firstName` और`lastName` से `fullName` की गणना कर सकते हैं
👍

2023-03-19 12:17 UTC, BrijenMakwana commented
> Thank you for working on the fixes.
> 
> 
> 
> I have added some more reviews till line 375.
> 
> 
> 
> Let's get these fixed and post that we can continue further with the review.

@arshadkazmi42 Changes have been made, it's a request to provide a review 👍

2023-04-28 17:28 UTC, arshadkazmi42 requested changes
Added more reviews till line 818.

Lets get these fixed and then we can continue further.

2023-04-28 17:28 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +यह मेनू लिस्ट कौम्पोनॅन्ट आपको कई में से एक यात्रा नाश्ता चुनने देता है:
```suggestion
यह मेनू लिस्ट कौम्पोनॅन्ट आपको कई यात्रा के नास्ते में से एक यात्रा नाश्ता चुनने देता है:
```

2023-04-28 17:28 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +वर्तमान में, यह सिलेक्टेड आइटम को `selectedItem` state वेरिएबल में एक ऑब्जेक्ट के रूप में संग्रहीत करता है। हालाँकि, यह बहुत अच्छा नहीं है: **`selectedItem` में शामिल कंटेंट `items` के भीतर से एक आइट
```suggestion
अभी, यह सिलेक्टेड आइटम को `selectedItem` state वेरिएबल में एक ऑब्जेक्ट के रूप में रखता है। हालाँकि, यह बहुत अच्छा नहीं है: **`selectedItem` में शामिल कंटेंट `items` में से एक आइटम के समान ऑब्जेक्ट है।** इसका मतलब है कि आइटम के बारे में जानकारी दो जगहों पर डुप्लिकेट है।
```

2023-04-28 17:28 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +यह समस्या क्यों है? आइए प्रत्येक item को एडिटेबल बनाएं:
```suggestion
यह समस्या क्यों है? आइए हर एक item को एडिटेबल बनाएं:
```

2023-04-28 17:28 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +इटम पर "Choose" पर क्लिक करते हैं और फिर उसे *एडिट* करते हैं, **इनपुट अपडेट होता है लेकिन नीचे का लेबल एडिट को रिफ्लेक्ट नहीं करता है।** ऐसा इसलिए है क्योंकि आपके पास डुप्लिकेट state है, और आप `selec
```suggestion
ध्यान दें की कैसे जब आप पहले आइटम के "Choose" पर क्लिक करते हैं और फिर उसे *एडिट* करते हैं, **इनपुट अपडेट होता है लेकिन नीचे का लेबल एडिट को रिफ्लेक्ट नहीं करता है।** ऐसा इसलिए है क्योंकि आपके पास डुप्लिकेट state है, और आप `selectedItem` को अपडेट करना भूल गए हैं।
```

2023-04-28 17:28 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +पर आप `selectedItem` को इसमें अपडेट कर सकते हैं, डुप्लिकेट को निकालना आसान हल है. इस उदाहरण में, एक `selectedItem` ऑब्जेक्ट के बजाय (जो `items` के अंदर ऑब्जेक्ट्स के साथ डुप्लिकेशंस बनाता है), आप sta
```suggestion
हालाँकि आप `selectedItem` को भी अपडेट कर सकते हैं, लेकिन डुप्लीकेशन को निकालना आसान हल होगा। इस उदाहरण में, एक `selectedItem` ऑब्जेक्ट के बजाय (जो `items` के अंदर ऑब्जेक्ट्स के साथ डुप्लिकेशंस बनाता है), आप state में `selectedId` रख सकते हैं, और फिर उस ID के साथ item को `items` array में खोजकर `selectedItem` प्राप्त कर सकते हैं:
```

2023-04-28 17:28 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +(वैकल्पिक रूप से, आप selected index को state में रख सकते हैं।)
```suggestion
(इसके बजाये, आप selected index को state में रख सकते हैं।)
```

2023-04-28 17:28 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +अब अगर आप *selected* item को एडिट करते हैं, तो नीचे दिया गया मैसेज तुरंत अपडेट हो जाएगा। ऐसा इसलिए है क्योंकि `setItems` फिर से रेंडर ट्रिगर करता है, और `items.find(...)` आइटम को अपडेट किया गया title
```suggestion
अब अगर आप *selected* item को एडिट करते हैं, तो नीचे दिया गया मैसेज तुरंत अपडेट हो जाएगा। ऐसा इसलिए है क्योंकि `setItems` फिर से रेंडर ट्रिगर करता है, और `items.find(...)` आइटम को अपडेट किये गए title के साथ ढूंढेगा। आपको *selected item* को state में रखने की ज़रूरत नहीं थी, क्योंकि केवल *selected ID* ही ज़रूरी है। बाकी की कैलकुलेशन रेंडर के दौरान की जा सकती है।
```

2023-04-29 04:49 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +यह मेनू लिस्ट कौम्पोनॅन्ट आपको कई में से एक यात्रा नाश्ता चुनने देता है:
👍🏻

2023-04-29 04:49 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +वर्तमान में, यह सिलेक्टेड आइटम को `selectedItem` state वेरिएबल में एक ऑब्जेक्ट के रूप में संग्रहीत करता है। हालाँकि, यह बहुत अच्छा नहीं है: **`selectedItem` में शामिल कंटेंट `items` के भीतर से एक आइट
👍🏻

2023-04-29 04:50 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +यह समस्या क्यों है? आइए प्रत्येक item को एडिटेबल बनाएं:
👍🏻

2023-04-29 04:50 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +इटम पर "Choose" पर क्लिक करते हैं और फिर उसे *एडिट* करते हैं, **इनपुट अपडेट होता है लेकिन नीचे का लेबल एडिट को रिफ्लेक्ट नहीं करता है।** ऐसा इसलिए है क्योंकि आपके पास डुप्लिकेट state है, और आप `selec
👍🏻

2023-04-29 04:50 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +पर आप `selectedItem` को इसमें अपडेट कर सकते हैं, डुप्लिकेट को निकालना आसान हल है. इस उदाहरण में, एक `selectedItem` ऑब्जेक्ट के बजाय (जो `items` के अंदर ऑब्जेक्ट्स के साथ डुप्लिकेशंस बनाता है), आप sta
👍🏻

2023-04-29 04:50 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +(वैकल्पिक रूप से, आप selected index को state में रख सकते हैं।)
👍🏻

2023-04-29 04:50 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +अब अगर आप *selected* item को एडिट करते हैं, तो नीचे दिया गया मैसेज तुरंत अपडेट हो जाएगा। ऐसा इसलिए है क्योंकि `setItems` फिर से रेंडर ट्रिगर करता है, और `items.find(...)` आइटम को अपडेट किया गया title
👍🏻

2023-04-29 04:51 UTC, BrijenMakwana commented
@arshadkazmi42  I have made the changes.

2023-05-27 04:41 UTC, BrijenMakwana commented
@arshadkazmi42 My pull request is open for almost 3 months now. It's a request to provide a review soon so it can be merged.

2023-05-27 10:41 UTC, arshadkazmi42 commented
@BrijenMakwana Thank you for the reminder and your patience. I am a bit busy and will be going through it soon.

2023-05-27 11:47 UTC, arshadkazmi42 requested changes
Thank you for working on the fixes.

I have added review to rest of the file, once these are fixed we can get this merged

2023-05-27 11:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +ता है कि कितने आइटम पैक किए गए हैं और कुल मिलाकर कितने आइटम हैं। यह पहली बार में काम करने लगता है, लेकिन यह बग्गी है। उदाहरण के लिए, यदि आप किसी आइटम को पैक करते हैं और फिर उसे हटा देते हैं, तो काउंट
```suggestion
इस पैकिंग लिस्ट में एक फुटर है जो दिखता है कि कितने आइटम पैक किए गए हैं और कुल मिलाकर कितने आइटम हैं। यह पहली बार में काम करने लगता है, लेकिन यह बग्गी है। उदाहरण के लिए, यदि आप किसी आइटम को पैक करते हैं और फिर उसे हटा देते हैं, तो काउंटर ठीक से अपडेट नहीं होता है। काउंटर को ठीक करें ताकि यह हमेशा सही रहे।
```

2023-05-27 11:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +हालांकि आप प्रत्येक event handler को `total` और `packed` काउंटरों को सही ढंग से अपडेट करने के लिए सावधानी से बदल सकते हैं, मूल मुसीबत यह है कि ये state वेरिएबल मौजूद हैं। वे निरर्थक हैं क्योंकि आप हम
```suggestion
हालांकि आप प्रत्येक event handler को `total` और `packed` काउंटरों को सही ढंग से अपडेट करने के लिए सावधानी से बदल सकते हैं, रुट समस्या यह है कि ये state वेरिएबल मौजूद हैं। वे निरर्थक हैं क्योंकि आप हमेशा `item` array से ही आइटमों की संख्या (packed या total) को कैलकुलेट कर सकते हैं। बग को ठीक करने के लिए रीडंडंट state को हटा दें:
```

2023-05-27 11:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +ध्यान दें कि इस परिवर्तन के बाद event handlers केवल `setItems` को कॉल करने से कैसे संबंधित हैं। आइटम की गणना अब `items` से अगले रेंडर के दौरान की जाती है, इसलिए वे हमेशा अप-टू-डेट रहते हैं।
```suggestion
ध्यान दें कि इस परिवर्तन के बाद event handlers केवल `setItems` को कॉल करने से कैसे संबंधित हैं। आइटम का काउंट अब `items` से अगले रेंडर के दौरान कैलकुलेट किया जाता है, इसलिए वे हमेशा अप-टू-डेट रहता है।
```

2023-05-27 11:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +### गायब होने वाले सिलेक्शन को ठीक करें {/*fix-the-disappearing-selection*/}
```suggestion
### गायब होने वाले सेलेक्शन को ठीक करें {/*fix-the-disappearing-selection*/}
```

2023-05-27 11:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +State में `letters` की एक लिस्ट है। जब आप किसी विशेष अक्षर पर हॉवर या फ़ोकस करते हैं, तो वह हाइलाइट हो जाता है। वर्तमान में हाइलाइट किया गया अक्षर `highlightedLetter` state वेरिएबल में संग्रहित है। आ
```suggestion
State में `letters` की एक लिस्ट है। जब आप किसी विशेष अक्षर पर होवर या फ़ोकस करते हैं, तो वह हाइलाइट हो जाता है। अभी हाइलाइट किया गया अक्षर `highlightedLetter` state वेरिएबल में संग्रहित है। आप अलग-अलग अक्षरों को "Star" और "Unstar" कर सकते हैं, जो state में `letters` array को अपडेट करता है।
```

2023-05-27 11:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +समस्या यह है कि आप letter ऑब्जेक्ट को `highlightedLetter` में स्टोर कर रहे हैं। लेकिन आप 'letters' array में भी वही जानकारी रखते हैं। तो आपके state में डुप्लीकेशन है! जब आप बटन क्लिक करने के बाद `let
```suggestion
समस्या यह है कि आप letter ऑब्जेक्ट को `highlightedLetter` में स्टोर कर रहे हैं। लेकिन आप `letters` array में भी वही जानकारी रखते हैं। तो आपके state में डुप्लीकेशन है! जब आप बटन क्लिक करने के बाद `letters` array को अपडेट करते हैं, आप एक नया अक्षर ऑब्जेक्ट बनाते हैं जो `highlightedLetter` से अलग है। यही कारण है कि `highlightedLetter === letter` चेक `false` हो जाता है, और हाइलाइट गायब हो जाता है। अगली बार जब आप पॉइंटर के हिलने पर `setHighlightedLetter` को कॉल करते हैं तो यह फिर से दिखाई देता है।
```

2023-05-27 11:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +### मल्टीप्ल सिलेक्शन इम्प्लीमेंट करें {/*implement-multiple-selection*/}
```suggestion
### मल्टीप्ल सेलेक्शन इम्प्लीमेंट करें {/*implement-multiple-selection*/}
```

2023-05-27 11:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +इस उदाहरण में, प्रत्येक `Letter` में एक `isSelected` prop और एक `onToggle` handler है जो इसे सिलेक्ट करता है। यह काम करता है, लेकिन state को `selectedId` के रूप में स्टोर किया जाता है (या तो `null` य
```suggestion
इस उदाहरण में, प्रत्येक `Letter` में एक `isSelected` prop और एक `onToggle` handler है जो इसे सेलेक्ट करता है। यह काम करता है, लेकिन state को `selectedId` के रूप में स्टोर किया जाता है (या तो `null` या एक ID), इसलिए किसी भी समय केवल एक ही अक्षर सिलेक्ट किया जा सकता है।
```

2023-05-27 11:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +मल्टीप्ल सिलेक्शन इम्प्लीमेंट करने के लिए state स्ट्रक्चर बदलें। (आप इसे कैसे स्ट्रक्चर करेंगे? कोड लिखने से पहले इसके बारे में सोचें।) प्रत्येक चेकबॉक्स दूसरों से स्वतंत्र होना चाहिए। किसी सिलेक्टेड
```suggestion
मल्टीप्ल सिलेक्शन इम्प्लीमेंट करने के लिए state स्ट्रक्चर बदलें। (आप इसे कैसे स्ट्रक्चर करेंगे? कोड लिखने से पहले इसके बारे में सोचें।) प्रत्येक चेकबॉक्स दूसरों से स्वतंत्र होना चाहिए। किसी सेलेक्टेड अक्षर पर क्लिक करने से उसे अनचेक कर देना चाहिए। अंत में, फुटर को सेलेक्टेड आइटम्स की सही संख्या दर्शानी चाहिए।
```

2023-05-27 11:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +एक ही selected ID के बजाय, आप एक array रखना चाह सकते हैं या state में selected IDs का [set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)।
```suggestion
एक ही selected ID के बजाय, आप एक array या selected IDs का [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) state में रखना चाह सकते हैं।
```

2023-05-27 11:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +एक `selectedId` के बजाय, `selectedIds` *array* को state में रखें। उदाहरण के लिए, यदि आप पहले और अंतिम अक्षर का सिलेक्शन करते हैं, इसमें `[0, 2]` होगा। जब कुछ भी नहीं चुना जाता है, तो यह एक खाली `[]`
```suggestion
एक `selectedId` के बजाय, `selectedIds` *array* को state में रखें। उदाहरण के लिए, यदि आप पहले और अंतिम अक्षर का सेलेक्शन करते हैं, इसमें `[0, 2]` होगा। जब कुछ भी नहीं चुना जाता है, तो यह एक खाली `[]` array होगा:
```

2023-05-27 11:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +एक array का उपयोग करने का एक मामूली नकारात्मक पहलू यह है कि प्रत्येक आइटम के लिए, आप `selectedIds.includes(letter.id)` को कॉल कर रहे हैं यह जांचने के लिए कि यह सिलेक्टेड है या नहीं। अगर array बहुत बड
```suggestion
एक array का उपयोग करने का एक मामूली नकारात्मक पहलू यह है कि प्रत्येक आइटम के लिए, आप `selectedIds.includes(letter.id)` को कॉल कर रहे हैं यह जांचने के लिए कि यह सेलेक्टेड है या नहीं। अगर array बहुत बड़ा है, यह एक परफ़ॉर्मेंस मुसीबत बन सकती है क्योंकि [`includes()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) के साथ array खोज लिनियर समय लेती है, और आप यह खोज प्रत्येक व्यक्तिगत आइटम के लिए कर रहे हैं।
```

2023-05-27 11:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +इसे ठीक करने के लिए, आप [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) को state में रख सकते हैं, जो एक तेज़ [`has()`](https://developer.mozilla.org/en-US/
```suggestion
इसे ठीक करने के लिए, आप [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) को state में रख सकते हैं, जो एक तेज़ [`has()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has) ऑपरेशन प्रोवाइड है:
```

2023-05-27 11:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/choosing-the-state-structure.md
> +ध्यान रखें कि आप [state में ऑब्जेक्ट्स को म्यूटेट नहीं करना चाहिए](/learn/updating-objects-in-state), और इसमें Sets भी शामिल हैं। यही कारण है कि `handleToggle` फ़ंक्शन पहले सेट की एक *कॉपी* बनाता है,
```suggestion
ध्यान रखें कि आपको [state में ऑब्जेक्ट्स को म्यूटेट नहीं करना है](/learn/updating-objects-in-state), और इसमें Sets भी शामिल हैं। यही कारण है कि `handleToggle` फ़ंक्शन पहले सेट की एक *कॉपी* बनाता है, और फिर उस कॉपी को अपडेट करता है।
```

2023-05-27 12:32 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +अब मान लें कि आप किसी ऐसे स्थान को हटाने के लिए एक बटन जोड़ना चाहते हैं, जहां आप पहले जा चुके हैं। आप इसे कैसे करेंगे? [नेस्टेड state को अपडेट करने](/learn/updating-objects-and-arrays-in-state#updati
👍🏻

2023-05-27 12:32 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +**यदि state आसानी से अपडेट करने के लिए नेस्टेड है, तो इसे "फ्लैट" बनाने पर विचार करें।** यहाँ एक तरीका है जिससे आप इस डेटा को रीस्ट्रक्चर कर सकते हैं। एक पेड़ जैसी स्ट्रक्चर के बजाय जहां प्रत्येक `pl
👍🏻

2023-05-27 12:32 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +- इसके मूल स्थान के अपडेट किए गए वर्जन को हटाई गई ID को उसके `childIds` array से बाहर करना चाहिए।
👍🏻

2023-05-27 12:32 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +आदर्श रूप से, आप मेमोरी उपयोग को बेहतर बनाने के लिए हटाए गए आइटम (और उनके चिल्ड्रन!) को "टेबल" ऑब्जेक्ट से हटा देंगे। यह वर्जन ऐसा करता है। यह [Immer का भी उपयोग करता है](/learn/updating-objects-in-s
👍🏻

2023-05-27 12:32 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +* रिडेन्डेन्ट और डुप्लिकेट स्थिति से बचें ताकि आपको इसे सिंक में रखने की ज़रूरत न हो।
👍🏻

2023-05-27 12:33 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +इस `Clock` कौम्पोनॅन्ट को दो prop मिलते हैं: `color` और `time`। जब आप सिलेक्ट बॉक्स में एक अलग रंग चुनते हैं, `Clock` कौम्पोनॅन्ट अपने पैरेंट कौम्पोनॅन्ट से एक अलग `color` prop प्राप्त करता है। हालाँ
👍🏻

2023-05-27 12:33 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +ता है कि कितने आइटम पैक किए गए हैं और कुल मिलाकर कितने आइटम हैं। यह पहली बार में काम करने लगता है, लेकिन यह बग्गी है। उदाहरण के लिए, यदि आप किसी आइटम को पैक करते हैं और फिर उसे हटा देते हैं, तो काउंट
👍🏻

2023-05-27 12:33 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +हालांकि आप प्रत्येक event handler को `total` और `packed` काउंटरों को सही ढंग से अपडेट करने के लिए सावधानी से बदल सकते हैं, मूल मुसीबत यह है कि ये state वेरिएबल मौजूद हैं। वे निरर्थक हैं क्योंकि आप हम
👍🏻

2023-05-27 12:33 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +ध्यान दें कि इस परिवर्तन के बाद event handlers केवल `setItems` को कॉल करने से कैसे संबंधित हैं। आइटम की गणना अब `items` से अगले रेंडर के दौरान की जाती है, इसलिए वे हमेशा अप-टू-डेट रहते हैं।
👍🏻

2023-05-27 12:33 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +### गायब होने वाले सिलेक्शन को ठीक करें {/*fix-the-disappearing-selection*/}
👍🏻

2023-05-27 12:33 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +State में `letters` की एक लिस्ट है। जब आप किसी विशेष अक्षर पर हॉवर या फ़ोकस करते हैं, तो वह हाइलाइट हो जाता है। वर्तमान में हाइलाइट किया गया अक्षर `highlightedLetter` state वेरिएबल में संग्रहित है। आ
👍🏻

2023-05-27 12:33 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +समस्या यह है कि आप letter ऑब्जेक्ट को `highlightedLetter` में स्टोर कर रहे हैं। लेकिन आप 'letters' array में भी वही जानकारी रखते हैं। तो आपके state में डुप्लीकेशन है! जब आप बटन क्लिक करने के बाद `let
👍🏻

2023-05-27 12:34 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +### मल्टीप्ल सिलेक्शन इम्प्लीमेंट करें {/*implement-multiple-selection*/}
👍🏻

2023-05-27 12:34 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +इस उदाहरण में, प्रत्येक `Letter` में एक `isSelected` prop और एक `onToggle` handler है जो इसे सिलेक्ट करता है। यह काम करता है, लेकिन state को `selectedId` के रूप में स्टोर किया जाता है (या तो `null` य
👍🏻

2023-05-27 12:34 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +मल्टीप्ल सिलेक्शन इम्प्लीमेंट करने के लिए state स्ट्रक्चर बदलें। (आप इसे कैसे स्ट्रक्चर करेंगे? कोड लिखने से पहले इसके बारे में सोचें।) प्रत्येक चेकबॉक्स दूसरों से स्वतंत्र होना चाहिए। किसी सिलेक्टेड
👍🏻

2023-05-27 12:34 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +एक ही selected ID के बजाय, आप एक array रखना चाह सकते हैं या state में selected IDs का [set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)।
👍🏻

2023-05-27 12:34 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +एक `selectedId` के बजाय, `selectedIds` *array* को state में रखें। उदाहरण के लिए, यदि आप पहले और अंतिम अक्षर का सिलेक्शन करते हैं, इसमें `[0, 2]` होगा। जब कुछ भी नहीं चुना जाता है, तो यह एक खाली `[]`
👍🏻

2023-05-27 12:35 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +एक array का उपयोग करने का एक मामूली नकारात्मक पहलू यह है कि प्रत्येक आइटम के लिए, आप `selectedIds.includes(letter.id)` को कॉल कर रहे हैं यह जांचने के लिए कि यह सिलेक्टेड है या नहीं। अगर array बहुत बड
👍🏻

2023-05-27 12:35 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +इसे ठीक करने के लिए, आप [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) को state में रख सकते हैं, जो एक तेज़ [`has()`](https://developer.mozilla.org/en-US/
👍🏻

2023-05-27 12:35 UTC, BrijenMakwana commented on beta/src/pages/learn/choosing-the-state-structure.md
> +ध्यान रखें कि आप [state में ऑब्जेक्ट्स को म्यूटेट नहीं करना चाहिए](/learn/updating-objects-in-state), और इसमें Sets भी शामिल हैं। यही कारण है कि `handleToggle` फ़ंक्शन पहले सेट की एक *कॉपी* बनाता है,
👍🏻

2023-05-27 12:36 UTC, BrijenMakwana commented
@arshadkazmi42 I have made all the changes. You can merge it. 😀

2023-05-27 15:46 UTC, arshadkazmi42 commented
Thank you @BrijenMakwana for working on this. There seems to be a conflict. Can you fix those conflicts? post that we can get this merged.

2023-05-28 07:34 UTC, arshadkazmi42 commented
@BrijenMakwana I see a lot of changes which are not related to this PR in the last commit. Can you revert the last commit and resolve the conflicts only from this file `src/content/learn/choosing-the-state-structure.md` 

Let me know if you need any help with it.

2023-05-28 08:49 UTC, BrijenMakwana commented
> @BrijenMakwana I see a lot of changes which are not related to this PR in the last commit. Can you revert the last commit and resolve the conflicts only from this file `src/content/learn/choosing-the-state-structure.md` 
> 
> Let me know if you need any help with it.

Sure. I'm working on it. Will let you know

2023-05-28 11:00 UTC, BrijenMakwana commented
> Please check if it can be merged now.

2023-05-28 13:00 UTC, arshadkazmi42 approved these changes

2023-05-28 13:04 UTC, merged

2023-05-28 13:05 UTC, arshadkazmi42 commented
Thank you @BrijenMakwana for working on this and thank you for your patience working on all the fixes.

2023-05-28 15:13 UTC, BrijenMakwana commented
> Thank you @BrijenMakwana for working on this and thank you for your patience working on all the fixes.

Thank you very much. I enjoyed working on it 🙂