English to Hindi: Referencing values with refs
reactjs/hi.react.dev pull request #222
Opened 2023-03-26 10:21 UTC by khizarq313

2023-04-28 17:44 UTC, arshadkazmi42 requested changes
Thank you for working on this. I have added review comments till line 44. 

Let's get these fixed then we can continue further with the review.

To know more about our review process check #23

2023-04-28 17:44 UTC, arshadkazmi42 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +जब आप किसी कंपोनेंट को कुछ जानकारी "याद" करवाना चाहते हों, लेकिन आप नहीं चाहते कि वह जानकारी [नए रेंडर को ट्रिगर करे](/learn/render-and-commit),तब आप एक *ref * का उपयोग कर सकते हैं।
```suggestion
जब आप किसी कौम्पोनॅन्ट को कुछ जानकारी "याद" रखवाना चाहते हों, लेकिन आप नहीं चाहते कि वह जानकारी [नए रेंडर को ट्रिगर करे](/learn/render-and-commit), तब आप एक *ref * का उपयोग कर सकते हैं।
```

2023-04-28 17:44 UTC, arshadkazmi42 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +- अपने कंपोनेंट में refs कैसे जोड़ें
`कंपोनेंट` => `कौम्पोनॅन्ट`

update all the references of this in the whole file. You can do a find and replace

2023-04-28 17:44 UTC, arshadkazmi42 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +- अपने कंपोनेंट में refs कैसे जोड़ें
```suggestion
- अपने कौम्पोनॅन्ट में refs कैसे ऐड करें
```

2023-04-28 17:44 UTC, arshadkazmi42 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +- refs के वैल्यू को कैसे अपडेट करें
```suggestion
- ref के वैल्यू को कैसे अपडेट करें
```

2023-04-28 17:44 UTC, arshadkazmi42 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +- refs state से कैसे अलग होते हैं
```suggestion
- ref state से कैसे अलग होते हैं
```

2023-04-28 17:44 UTC, arshadkazmi42 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +- refs को सुरक्षित तरीके से कैसे उपयोग करें
```suggestion
- ref को सुरक्षित तरीके से कैसे उपयोग करें
```

2023-04-28 17:44 UTC, arshadkazmi42 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +## अपने कंपोनेंट में refs जोड़ना {/*adding-a-ref-to-your-component*/}
```suggestion
## अपने कौम्पोनॅन्ट में ref ऐड करना {/*adding-a-ref-to-your-component*/}
```

2023-04-28 17:44 UTC, arshadkazmi42 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +आप React से `useRef` हुक इम्पोर्ट करके अपने कंपोनेंट में एक refs जोड़ सकते हैं:
```suggestion
आप React से `useRef` हुक इम्पोर्ट करके अपने कौम्पोनॅन्ट में एक ref ऐड कर सकते हैं:
```

2023-04-28 17:44 UTC, arshadkazmi42 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +अपने कंपोनेंट के अंदर, `useRef` हुक को कॉल करें और प्रारंभिक वैल्यू पास करें जिसे आप केवल तर्क के रूप में रेफरन्स करना चाहते हैं। उदाहरण के लिए, यहां वैल्यू `0` के लिए एक refs है:
```suggestion
अपने कौम्पोनॅन्ट के अंदर, `useRef` हुक को कॉल करें और इनिशियल वैल्यू पास करें जिसे आप केवल आर्गुमेंट के रूप में रेफरन्स करना चाहते हैं। उदाहरण के लिए, यहां वैल्यू `0` के लिए एक ref है:
```

2023-04-28 17:44 UTC, arshadkazmi42 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +`useRef` एक इस तरह के ऑब्जेक्ट को वापस करता है:
```suggestion
`useRef` एक इस तरह के ऑब्जेक्ट को रिटर्न करता है:
```

2023-04-28 19:32 UTC, khizarq313 commented
> @khizarq313 I have added some review comments. Can you fix those, also can you fix the conflict we are seeing in one of the file.

sure, I will take a look at it asap.

2023-04-29 06:46 UTC, closed without merging

2023-04-29 09:13 UTC, arshadkazmi42 commented
@khizarq313 Looks like you did a force push which removed all the changes and I am seeing the PR is closed. Are you going to open a new PR?

2023-04-29 10:35 UTC, khizarq313 commented
i was trying to fix the conflict and there was a massage saying that my repository is one commit ahead, i thought that might be causing the conflict so i pressed the sync button...and this happened.. sorry for the trouble i caused...
I am working on translation and yes i will open new pr.

2023-04-29 10:46 UTC, khizarq313 commented
I am correcting my translation,also i am reffering hindi glossary page 
(https://github.com/reactjs/hi.react.dev/issues/2),

i still don't know the reason behind the previously faced conflict,
I need you to clarify me somethings,
this is my first contribution,
i fork the hi.reactjs.org repo then clone it locally,
After translation i should commit it and ask for review through pull request?
am i doing it correctly, or should i need to correct myself ?
any clarification is appricate and i am sorry for my inconvinence.

2023-04-29 12:08 UTC, arshadkazmi42 commented
Yes. it is correct. Only one thing you need to consider is your fork could get out of sync from the main repository and you will have to sync it with the main repository 

You can refer this stackoverflow on how to do this https://stackoverflow.com/a/7244456/3136282

Or I have created a cli tool for this [upfork](https://github.com/gh-conf/upfork) you could also use this.

2023-04-29 12:52 UTC, khizarq313 commented
sure, I will go with cli tool as it seems simple and easy to use.
Thank you!

2023-05-01 14:36 UTC, khizarq313 commented
Hey!
What should i write in hindi for word "unreliable",

English:
This is why reading `ref.current` during render leads to unreliable code. If you need that, use state instead.
Hindi:
इसीलिए रेंडर के दौरान `ref.current` को पढ़ने से कोड अविश्वसनीय (unreliable) होजाता है। अगर आपको उसकी जरूरत है, तो ref के बजाय state का इस्तेमाल करें।

one more thing...
how should i write this: "escape hatch" or "एस्केप हैच"

2023-05-01 15:03 UTC, khizarq313 commented
also what should i use for word: synchronously or तुल्यकालिकत ?

2023-05-05 19:19 UTC, arshadkazmi42 commented
@khizarq313 We can use following

`synchronously` => `सिंक्रोनोसली`
 `unreliable` => `अनरीलाऐबल`

`एस्केप हैच` will be better