docs: Translate "Using TypeScript" page to Hindi
reactjs/hi.react.dev pull request #266
Opened 2023-12-26 08:06 UTC by sohail-313

This pull request addresses issue #168.

### Changes Proposed
Translated the "Using TypeScript" page in the React documentation to Hindi.

### Recording
https://github.com/reactjs/hi.react.dev/assets/85786620/59eefa3d-c619-4518-90ea-38d5e6c67dcd

### Note to Reviewers
No specific notes for reviewers at the moment. The changes are straightforward and align with the outlined translation task. If you have any questions or suggestions, please feel free to let me know.

2023-12-29 04:16 UTC, sohail-313 commented
@arshadkazmi42 can you validate this if you are free, It has been three days

2024-01-08 16:39 UTC, arshadkazmi42 commented
> @arshadkazmi42 can you validate this if you are free, It has been three days

@sohail-313 Sorry for the delay. I will get to it asap. I have been a bit occupied.

2024-05-11 10:40 UTC, arshadkazmi42 commented on src/content/learn/typescript.md
> +title: टाइपस्क्रिप्ट का उपयोग
```suggestion
title: TypeScript का उपयोग
```

lets not translate `TypeScript` word

2024-05-11 10:42 UTC, arshadkazmi42 commented on src/content/learn/typescript.md
> +टाइपस्क्रिप्ट एक पॉपुलर तरीका है जिससे जावास्क्रिप्ट कोडबेस में टाइप डेफिनीशन जोड़ी जा सकती है। टाइपस्क्रिप्ट [JSX](/learn/writing-markup-with-jsx) को समर्थन करता है, और आप अपनें परियोजना में [`@type
```suggestion
टाइपस्क्रिप्ट एक पॉपुलर तरीका है जिससे जावास्क्रिप्ट कोडबेस में टाइप डेफिनीशन ऐड की जा सकती है। टाइपस्क्रिप्ट [JSX](/learn/writing-markup-with-jsx) को सपोर्ट करता है, और आप अपनें प्रोजेक्ट में [`@types/react`](https://www.npmjs.com/package/@types/react) and [`@types/react-dom`](https://www.npmjs.com/package/@types/react-dom) जोड़कर पूर्ण React वेब सपोर्ट प्राप्त कर सकते हैं।
```

2024-05-11 10:42 UTC, arshadkazmi42 commented on src/content/learn/typescript.md
> +टाइपस्क्रिप्ट एक पॉपुलर तरीका है जिससे जावास्क्रिप्ट कोडबेस में टाइप डेफिनीशन जोड़ी जा सकती है। टाइपस्क्रिप्ट [JSX](/learn/writing-markup-with-jsx) को समर्थन करता है, और आप अपनें परियोजना में [`@type
Add a line break at line 7

2024-05-11 10:43 UTC, arshadkazmi42 commented on src/content/learn/typescript.md
> +* [टाइपस्क्रिप्ट के साथ रिएक्ट कंपोनेंट्स:](/learn/typescript#typescript-with-react-components)
```suggestion
* [टाइपस्क्रिप्ट के साथ React कौम्पोनॅन्टस](/learn/typescript#typescript-with-react-components)
```

Update whole file to use `React` and for components use `कौम्पोनॅन्टस`

2024-05-11 10:43 UTC, arshadkazmi42 commented on src/content/learn/typescript.md
> +* [हुक्स के साथ टाइपिंग के उदाहरण](/learn/typescript#example-hooks)
```suggestion
* [Hooks के साथ टाइपिंग के उदाहरण](/learn/typescript#example-hooks)
```

lets not translate React related keywords

2024-05-11 10:44 UTC, arshadkazmi42 commented on src/content/learn/typescript.md
> +* [सामान्य प्रकारें से `@types/react`](/learn/typescript/#useful-types)
```suggestion
* [`@types/react` से कॉमन टाइप्स](/learn/typescript/#useful-types)
```

2024-05-11 10:45 UTC, arshadkazmi42 commented on src/content/learn/typescript.md
> +सभी [प्रोडक्शन-ग्रेड रिएक्ट फ्रेमवर्क्स](/learn/start-a-new-react-project#production-grade-react-frameworks) टाइपस्क्रिप्ट का समर्थन करते हैं। स्थापना के लिए फ्रेमवर्क विशिष्ट गाइड का पालन करें:
```suggestion
सभी [प्रोडक्शन-ग्रेड React फ्रेमवर्क्स](/learn/start-a-new-react-project#production-grade-react-frameworks) TypeScript को सपोर्ट करते हैं। इंस्टालेशन के लिए फ्रेमवर्क विशिष्ट गाइड का पालन करें:
```

2024-05-11 10:45 UTC, arshadkazmi42 commented on src/content/learn/typescript.md
>  ## Installation {/*installation*/}
```suggestion
## इंस्टालेशन {/*installation*/}
```

translate titles as well

2024-05-11 10:45 UTC, arshadkazmi42 commented on src/content/learn/typescript.md
> +###  मौजूदा रिएक्ट परियोजना में टाइपस्क्रिप्ट जोड़ना {/*adding-typescript-to-an-existing-react-project*/}
```suggestion
### मौजूदा React प्रोजेक्ट में TypeScript ऐड करना {/*adding-typescript-to-an-existing-react-project*/}
```

2024-05-11 10:46 UTC, arshadkazmi42 commented on src/content/learn/typescript.md
> +लेटेस्ट वर्शन की रिएक्ट के टाइप डेफिनीशन्स को स्थापित करने के लिए:
```suggestion
लेटेस्ट वर्शन React के टाइप डेफिनीशन्स को इनस्टॉल करने के लिए:
```

2024-05-11 10:47 UTC, arshadkazmi42 requested changes
Thank you for taking time and working on this.

I have added comments till line 35. Let's get these fixed before continuing further with review.

I will also suggest making the suggested changes in whole file using find & replace will speed up the review process

2024-09-30 21:20 UTC, arshadkazmi42 approved these changes

2024-09-30 21:20 UTC, arshadkazmi42 commented
Merging this and we can take care of comments in a followup PR

2024-09-30 21:26 UTC, merged